[package]
name = "table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datasize = { git = "https://github.com/s3bk/datasize-rs" }
serde = { version = "*", features = ["derive"] }
